export const productEnums = [
	"Air Conditioner",
	"Water Heater",
	"Microwave",
	"Geyser",
	"Refrigerator",
	"Washing Machine",
	"Air Cooler",
	"Air Purifier",
	"Water Purifier",
	"Deep Freezer",
	"Visi Cooler",
	"Cassette AC",
	"Water Cooler cum Purifier",
	"Water Dispenser",
	"Display Counter",
	"Back Bar Chiller",
	"Upright Chiller",
	"Food Prep Chiller",
	"Ice Maker",
];
